# This is a config for E2B sandbox template.
# You can use template ID (ae9b8fvi623hg8k92c2e) or template name (vibe-next-js-devmitrije010) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-next-js-devmitrije010") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-js-devmitrije010") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-js-devmitrije010')

team_id = "cb26c978-1acf-4c2d-96f2-2a981fac1493"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-js-devmitrije010"
template_id = "ae9b8fvi623hg8k92c2e"
